### ISSUE TITLE
Cloud Shell should not time out when running a command

### ISSUE THREAD

**Issue by inaun** [Azure/CloudShell#228]
I am trying to run a piped PowerShell command in Cloud Shell that takes a long time to complete. Cloud Shell keeps timing out before the process completes.

Cloud Shell should not time out and disconnect when a command is running.

**Comment by dsajanice** [comment]
How long was the command running? We have a 4 hour max usage time for all customers and a 20 minute timeout for inactivity. Cloud Shell might not be the best tool for your purpose. Please share more details about your scenario and we can evaluate.

**Comment by inaun** [comment]
Hi. Thanks for your response.

The reason I opened the issue is because there should not be any timeout when a command is running. Nor should there be a “max usage” time. Nor should I have to use “another tool” for the occasional long-running Powershell script.

Why do these limits exist? If I am administering my Azure environment, what is the advantage of restricting me to 4 hours of work in Cloud Shell? There are occasions when an engineer or admin needs to work from a location / system that cannot be easily configured with the normal toolsets.

I am in one of those situations now, which is why I chose to use Cloud Shell. Also, the issue I’m dealing with was an urgent issue that required “right now” response. Cloud Shell was my only option, and the timeouts only added frustration at a time where added stress/frustration was not helpful.

**Comment by maertendMSFT** [comment]
@inaun, yes I agree that having an unlimited timeout would be great.  Unfortunately, we cannot offer that experience at this time due to availability concerns for other users.  If all users have unlimited timeout, we would quickly run out of containers for folks who are requesting a session.

I have opened a discussion on this topic, https://github.com/Azure/CloudShell/discussions/230, please add your thoughts on this page.
